### ISSUE TITLE
Class Cast exception in loggerManager

### ISSUE THREAD

**Issue by Rahul-R5** [Rahul-R5/KoraKaagaz#49]
Log:
Exception in thread "main" java.lang.ClassCastException: class com.sun.xml.internal.stream.events.StartElementEvent cannot be cast to class javax.xml.stream.events.Characters (com.sun.xml.internal.stream.events.StartElementEvent and javax.xml.stream.events.Characters are in module java.xml of loader 'bootstrap')
	at java.xml/com.sun.xml.internal.stream.events.DummyEvent.asCharacters(DummyEvent.java:115)
	at korakaagaz/infrastructure.validation.logger.LoggerManager.configFileToParse(LoggerManager.java:123)
	at korakaagaz/infrastructure.validation.logger.LoggerManager.<init>(LoggerManager.java:66)
	at korakaagaz/infrastructure.validation.logger.LoggerFactory.getLoggerInstance(LoggerFactory.java:33)
	at korakaagaz/infrastructure.validation.testing.TestHarness.runByName(TestHarness.java:324)
	at korakaagaz/infrastructure.validation.testing.runner.main(runner.java:8)

Test harness and logger is the environment. The test harness is initialised by a main function. The exception occurs when the test harness tries to get a logger instance.

**Comment by Rahul-R5** [comment]
@navneeth Please see

**Comment by nmnambiar** [comment]
I think this shouldn't be happening
because when I checked for exceptions to be handled during reviewing, no method that I imported seemed to throw such an exception

let me see if I missed something

**Comment by nmnambiar** [comment]
okay, I think it seems like the `getData()` method that needs to be called by an object of `Characters` class was actually being called from a different class (the `StartElementEvent` class). 

This happens even though I had an object `startElement` of `StartElementEvent class` use `asCharacters()` method to get a corresponding object of `Characters` class. Guess it wasn't being implicitly done or something

For a possible fix, let me try having an explicit Characters object to do the work. Refer [here][SO-link]

[SO-link]:<https://stackoverflow.com/questions/58226860/get-element-text-by-looking-for-it-id-in-xml-stringtable-for-games-using-sta>

**Comment by nmnambiar** [comment]
can be closed @Rahul-R5
